### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#106]
Make some thoughts about presenting the app

**Comment by pswu11** [comment]
## Introduction (~5-10 min)

- What is the App about?
- Inspirations (From Sven, and ourselves who are job seekers) 
- What is the problem that we're solving (organizing the job search), what are people using for this problem right now (notion, excel), and why our app should be an improvement
- Target users: 
   - Who wants to get "employeed" (not targeting freelancers)
   - White colar jobs: tech industry, creative, ...  office jobs, etc. 
   - Who applies for many jobs and need to organize & track the applications 

- Design (Jacob) 
   - Choice of typography, color, UI theme, etc. ( and explain how this reflects the product image) 
   - Desktop vs. mobile app
   - Why we do have both Kanbanboard and Table views
   - Show the wireframes (rough design) and complete Figma 

- TechStack
   - TypeScript
   - Next.js, Tailwind CSS
   - Prisma, PostgreSQL, Clerk (Auth)
   - Other libraries: Tanstack Table, Tanstack Query, dnd-kit, ...etc.

## Demo (~15 min) 

### Part I: Demo the user onboarding process
- Start with a fresh account (❗ don't use email signup, use GitHub or Discord). 
  - Login, create a new column, rename a column, change the color of the column
  -  Create a new job, add tags, remove tags


### Part II: Demo with prepared account
- Prepare an account that already has 20+ jobs, and 15+ tags, to show actual scenarios 
   - Sort & filter jobs in table view
   - Delete a job, delete a column

### Part III: Outlook of the projects, what could still be added:
- User-defined table columns
- Extra view for archived jobs
- Easier filter (selectable)
- Add notifications for application deadlines
- Activity Log: Users can log notes and todos for each job
- Auto-fill the job form based on the job link (e.g. use Indeed API)

## Retrospective & Expericne at Devhaus (~10 min) 

- Lessons learned (from the final project) 
  - Design (ideation process, Figma, tooling, starting small vs starting big in design system) 
  - Development: 🐱 🌵 🍰 
  - Question: do all of us want to talk about the experience individually? Or we want to put together our thoughts and present as a group learning 

- Camp experience (overall the whole camp) 
  - we can discuss on Wed. 

## Q&A (5 min)

**Comment by JanHendryk** [comment]
It looks fine for me, we should practice it tomorrow to keep the time frame.

**Comment by Hottinho** [comment]
Thanks to Jacob and Pei for the outline. I like the general approach and structure very much already.
My notes/suggestions regarding the presentation as a whole:

### Length!

In my experience presentations usually tend to be on the longer side of the projected time-windows. Meaning, if someone says: "This is going to take 5-10 minutes", it ususally takes 10, at least :)
Adding the longest time frames for each of the sub-chapters, it would result in a 45 min presentation. That is rather lengthy. We should try to cut it down to the suggested 20-25 minute window. Usually, that will take 30 minutes in the end anyways.

### Present to our guests, not our teachers

The first outline does this already pretty well in the introduction. So this is just a reminder to present to people that will see this app for the first time. The majority of them will probably see this from a user perspective and have little to no experience with coding. Also, not everyone knows what a Kanban board is, for example. Let's keep this in mind, when presenting. 

### Explaining (parts of) TechStack as we go through the demo?

This more of a question arising from the previous point. 

For example: Is it smart to just introduce the language and basic framworks at the beginning of the tech-stack chapter and then explain our Clerk-auth solution during the first demo-login? Same with the database, drag&drop-stuff, etc?

### Retrospective and experience

I reckon since the experience levels are very diverse and -- at least for me -- also very much influenced by the somewhat rough and "makeshift" changes, it might be smart to make everybody just say a couple of short sentences, without going into too much detail on the adversity we faced in the second half.

**Comment by systm-spec** [comment]
I generally would like to keep the presentation rather shorter then longer.

Else I very much agree to @Hottinho, especially when it comes to TechStack Part.
So thinking about the right way to visualise it while in the demo might be needed.

**Comment by pswu11** [comment]
Project outlook: 
- [ ]     Extra view for archived jobs
- [ ]     Easier filter (selectable)
- [ ]     Add notifications for application deadlines
- [ ]     Activity Log: Users can log notes and todos for each job
- [ ]     Auto-fill the job form based on the job link (e.g. use Indeed API)
